/** Fix Latin a-z tokens from Tesseract OCR misreads in Nepali legal text. */

const DEVANAGARI = /[\u0900-\u097F]/;

/** Exact token replacements (case-insensitive match on token). */
const LATIN_TOKEN_FIXES: Record<string, string> = {
  ghee: "पूर्जी",
  the: "पूर्जी",
  tage: "पूर्जी",
  ghg: "पूर्जी",
  th: "पूर्जी",
  fet: "जफत",
  fee: "जफत",
  feal: "फौजदारी",
  fel: "फौजदारी",
  hel: "फौजदारी",
  fey: "फौजदारी",
  bye: "कसूर",
  are: "एमिकस",
  ater: "अनुसूची-३",
  aea: "बाँकी",
  tg: "पर्नेछ",
  wg: "पर्नेछ",
  wig: "पर्नेछ",
  gg: "पर्नेछ",
  tf: "पर्नेछ",
  tfg: "सक्नेछ",
  te: "पर्नेछ",
  eg: "पर्नेछ",
  gle: "धरौट",
  af: "बैङ्क",
  rel: "पैरबी",
  ul: "पैरबी",
  ffg: "सक्नेछ",
  geg: "पर्नेछ",
  teast: "पुनरावलोकन",
  we: "संलग्न",
  wre: "लिखाए",
  fiat: "परे",
  fia: "नबुझ",
  hag: "जफत",
  gate: "पुगे",
  der: "सम्बन्धित",
  en: "पर्नेछ",
  dw: "सात",
  dard: "पुग",
  dared: "बुझाउन",
  car: "र",
  fa: "फ",
  ag: "राख",
  ge: "पनि",
  gra: "मूल",
  ft: "धरौट",
  fy: "फिराद",
  ff: "फिर्ता",
  fi: "फिर्ता",
  fh: "विधि",
  fax: "कसूर",
  fat: "धरौट",
  fah: "पक्ष",
  fue: "सो",
  fuer: "सो",
  alae: "सरकारी",
  ale: "धरौट",
  ade: "धरौट",
  aare: "सम्बन्धी",
  aac: "परे",
  aeh: "अनुसूची-१",
  arh: "खण्ड",
  ast: "बाट",
  ba: "पर्नेछ",
  ci: "पर्नेछ",
  cy: "ङ",
  sy: "ङ",
  fg: "ङ",
  cn: "",
  es: "",
  jess: "",
  wann: "",
  con: "",
  herb: "",
  etre: "",
  che: "",
  hata: "",
  hea: "",
  hecht: "",
  heh: "",
  hal: "",
  gil: "",
  gag: "",
  gas: "धरौट",
  he: "धरौट",
  hech: "",
  kat: "",
  og: "",
  rf: "",
  rs: "",
  ty: "",
  wy: "",
  hex: "",
  srt: "",
  hhl: "",
  taht: "",
  ile: "",
  twh: "",
  wom: "",
  tog: "",
  hele: "",
  het: "",
  wel: "",
  feat: "भएको",
  tiate: "",
  ware: "",
  sued: "",
  freer: "अन्य",
  fiera: "व्यक्तिले",
  aft: "अनङ्कित",
  eae: "गर्न",
  ad: "आदेश",
  tag: "पूर्जी",
  tee: "",
  yel: "",
};

/** Regex-based phrase fixes (apply before token pass). */
const LATIN_PHRASE_FIXES: [RegExp, string][] = [
  [/फेला\s+FIAT/gi, "फेला परे"],
  [/FIAT\s+क्षति/gi, "जफत क्षति"],
  [/पक्राउ\s+TH\b/gi, "पक्राउ पूर्जी"],
  [/TH\s+जारी/gi, "पूर्जी जारी"],
  [/TH\s+भए/gi, "पूर्जी तामेल भए"],
  [/TH\s+हुन/gi, "पूर्जी हुन"],
  [/TH\s+भएको/gi, "पूर्जी भएको"],
  [/TH,\s/gi, "पूर्जी, "],
  [/जानकारी\s+WH\b/gi, "जानकारी तामेल"],
  [/\bWH\s+भए/gi, "तामेल भए"],
  [/सूचना\s+WH\b/gi, "सूचना तामेल"],
  [/परिच्छेद-९\s+ARE/gi, "परिच्छेद-९ एमिकस"],
  [/परिच्छेद\s*६\s+अन्तर्गत\s+GHEE/gi, "परिच्छेद-६ अन्तर्गत पूर्जी"],
  [/अनुसूची-१\s+वा\s+ATER/gi, "अनुसूची-१ वा अनुसूची-३"],
  [/२०७९\s+103139/g, "२०७९।०३।१३"],
  [/©\s*/g, ""],
  [/\[oA/g, ""],
  [/"\s*Eg\s*\|/g, " पर्नेछ |"],
  [/\bSy\)/g, "(ङ)"],
  [/\bCy\)/g, "(ङ)"],
  [/\bFg\)/g, "(ङ)"],
  [/\b9\s*\(/g, "("],
  [/sin\s*sis\s*g/gi, ""],
  [/JESS\s+cn\s+WANN/gi, ""],
  [/CHE\s+HATA/gi, "राखिएका"],
  [/HERB\s+ETRE/gi, ""],
  [/HECHT/gi, ""],
  [/FE\s+५५/g, "। ५५"],
  [/FE\s+बाहिर/g, " बाहिर"],
  [/FE\s+कुरा/g, " झुट्टा"],
  [/FEAL/gi, "फौजदारी"],
  [/FEY/gi, "फौजदारी"],
  [/FAX/gi, "कसूर"],
  [/FAT/gi, "धरौट"],
  [/FAH/gi, "पक्ष"],
  [/FUER/gi, "सो"],
  [/FIERA/gi, "व्यक्तिले"],
  [/Freer/gi, "अन्य"],
  [/AFT/gi, "अनङ्कित"],
  [/EAE/gi, "गर्न"],
  [/AAC/gi, "परे"],
  [/AEH/gi, "अनुसूची-१"],
  [/ARH/gi, "खण्ड"],
  [/AST/gi, "बाट"],
  [/Aare/gi, "सम्बन्धी"],
  [/alae/gi, "सरकारी"],
  [/BYE/gi, "कसूर"],
  [/Car/gi, "र"],
  [/GAG/gi, ""],
  [/GIL/gi, ""],
  [/GAS/gi, "धरौट"],
  [/GATE/gi, "पुगे"],
  [/Hag/gi, "जफत"],
  [/HAL/gi, ""],
  [/HEA/gi, "राख"],
  [/HEH/gi, ""],
  [/HECHT/gi, ""],
  [/HE\s/gi, " "],
  [/He,/gi, "धरौट,"],
  [/FI,/gi, "फिर्ता,"],
  [/FT\s/gi, "धरौट "],
  [/Gra,/gi, "मूल,"],
  [/FF\s/gi, "फिर्ता "],
  [/FY\s/gi, "फिराद "],
  [/Fy\s/gi, "बैङ्क "],
  [/dw\s+दिन/gi, "सात दिन"],
  [/dard\s+वा/gi, "पुग वा"],
  [/dared\s+दिन/gi, "बुझाउन दिन"],
  [/ern\s+तीस/gi, "अन्य तीस"],
  [/ae\s*\|/gi, "पर्नेछ |"],
  [/eG\s*\|/gi, "पर्नेछ |"],
  [/Eg\s*\|/gi, "पर्नेछ |"],
  [/GEG\s*\|/gi, "पर्नेछ |"],
  [/FFG\s*\|/gi, "सक्नेछ |"],
  [/TFG\s*\|/gi, "सक्नेछ |"],
  [/Tg\s*\|/gi, "पर्नेछ |"],
  [/TG\s*\|/gi, "पर्नेछ |"],
  [/TF\s*\|/gi, "पर्नेछ |"],
  [/Tf\s*/gi, "पर्नेछ "],
  [/wg\s*\|/gi, "पर्नेछ |"],
  [/wig\s*\|/gi, "पर्नेछ |"],
  [/gg\s*\|/gi, "पर्नेछ |"],
  [/TE:/gi, "पर्नेछ:"],
  [/TE\s/gi, "पर्नेछ "],
  [/TEAST/gi, "पुनरावलोकन"],
  [/Rel\s/gi, "पैरबी "],
  [/Ul\s/gi, "पैरबी "],
  [/THEE\s+तामेली/gi, "पूर्जी तामेली"],
  [/THEM\s+तामेल/gi, "पूर्जी तामेल"],
  [/SHEE\s+तामेल/gi, "पूर्जी तामेल"],
  [/WHEE\s+पूर्जी/gi, "तीन प्रति पूर्जी"],
  [/पक्राउ\s+TA\s+जारी/gi, "पक्राउ पूर्जी जारी"],
  [/THI\s+बुझाउन/gi, "बुझाउन"],
  [/Jae\s+तामेल/gi, "पूर्जी तामेल"],
  [/TAREE\s+म्याद/gi, "बाँकी म्याद"],
  [/TIA\s*पर्नेछ/gi, "नपर्ने"],
  [/TIT\s+प्रमाण/gi, "थप प्रमाण"],
  [/Ya\s*पर्नेछ/gi, "पर्नेछ"],
  [/WET\s+हर्ने/gi, "हाजिर"],
  [/WEE:/gi, "उजुर:"],
  [/\bSF\s+जमानत/gi, "बैङ्क जमानत"],
  [/\bHUT\s+गरेको/gi, "हट गरेको"],
  [/\bHT\s+बाहिरको/gi, "बाहिरको"],
  [/\bTed\s+फैसला/gi, "तर फैसला"],
  [/Sarg\)/gi, "(ङ)"],
  [/Ser\s+टाँसी/gi, "मा टाँसी"],
  [/\bTP\)/gi, "(ट)"],
  [/\bTER\)/gi, "(ङ)"],
  [/HIGHER!/gi, "व्यहोरा"],
  [/JAC\s+TTT\s+४/gi, ""],
  [/\bTTT\b/gi, ""],
  [/\bTT\b/gi, ""],
  [/TRA\s+मुद्दाको/gi, "साक्षी मुद्दाको"],
  [/TAT\s+प्रमाण/gi, "सङ्कलित प्रमाण"],
  [/~\s*WN\s+o\s+VN/gi, ""],
  [/sin\s*sis\s*g\s*ce\s*ङ\s*ही\s*सिसा/gi, ""],
  [/on\s+ला/gi, "ला"],
  [/\boo\./g, "१७०."],
  [/\blf\s+चलेको/gi, "पति चलेको"],
  [/\bHY\s+भएमा/gi, "हित भएमा"],
  [/TIA/gi, ""],
  [/TIT/gi, "थप"],
  [/THIGH/gi, ""],
  [/THI/gi, ""],
  [/THEE/gi, "पूर्जी"],
  [/THEM/gi, "पूर्जी"],
  [/SHEE/gi, "पूर्जी"],
  [/WHEE/gi, ""],
  [/WET/gi, "हाजिर"],
  [/WEE/gi, "उजुर"],
  [/TAREE/gi, "बाँकी"],
  [/TAT/gi, "सङ्कलित"],
  [/HUT/gi, "हट"],
  [/HT/gi, ""],
  [/HIGHER/gi, ""],
  [/HIG/gi, ""],
  [/SF/gi, "बैङ्क"],
  [/Jae/gi, "पूर्जी"],
  [/Ser/gi, "मा"],
  [/Sarg/gi, "ङ"],
  [/Ted/gi, "तर"],
  [/TRA/gi, "साक्षी"],
  [/Ya/gi, ""],
  [/VN/gi, ""],
  [/WN/gi, ""],
  [/HY/gi, "हित"],
  [/UE/gi, "१६८"],
  [/lf/gi, "पति"],
  [/ce/gi, ""],
  [/on/gi, ""],
  [/oo/gi, ""],
  [/TT/gi, ""],
  [/JAC/gi, ""],
  [/TP/gi, "ट"],
  [/TER/gi, "ङ"],
];

const LATIN_TOKEN_RE = /(?<![A-Za-z])([A-Za-z]{2,})(?![A-Za-z])/g;

function isDevanagariContext(text: string, index: number): boolean {
  const window = text.slice(Math.max(0, index - 40), index + 40);
  return DEVANAGARI.test(window);
}

export function fixLatinOcrArtifacts(text: string): string {
  let result = text;

  for (const [pattern, replacement] of LATIN_PHRASE_FIXES) {
    result = result.replace(pattern, replacement);
  }

  result = result.replace(LATIN_TOKEN_RE, (match, word: string, offset: number) => {
    if (!isDevanagariContext(result, offset)) return match;

    const key = word.toLowerCase();
    if (key in LATIN_TOKEN_FIXES) {
      const fix = LATIN_TOKEN_FIXES[key];
      return fix;
    }

    // Unknown short latin before punctuation — likely "पर्नेछ"
    if (word.length <= 4 && /^[A-Za-z]+$/.test(word)) {
      const after = result.slice(offset + word.length).trimStart();
      if (after.startsWith("|") || after.startsWith("।") || after.startsWith(",")) {
        return "पर्नेछ";
      }
    }

    return match;
  });

  // Collapse double spaces introduced by empty replacements
  result = result.replace(/[ \t]{2,}/g, " ");
  result = result.replace(/\s+\|/g, " |");
  result = result.replace(/\s+।/g, " ।");

  return result;
}
