/**
 * Deterministic Roman → Devanagari for common legal terms.
 * Applied before LLM translation so query embeddings match indexed chunk text.
 */

/** Multi-word phrases — longest / most specific first. */
const PHRASE_REPLACEMENTS: ReadonlyArray<[RegExp, string]> = [
  [/likhit\s+prat[iu]?tuttar\s+patra/gi, "लिखित प्रतिउत्तरपत्र"],
  [/likhit\s+prat[iu]?uttar\s*patra/gi, "लिखित प्रतिउत्तरपत्र"],
  [/likhit\s+prat[iu]?tuttar/gi, "लिखित प्रतिउत्तर"],
  [/prat[iu]?tuttar\s+patra/gi, "प्रतिउत्तरपत्र"],
  [/prat[iu]?uttar\s*patra/gi, "प्रतिउत्तरपत्र"],
  [/written\s+reply/gi, "लिखित प्रतिउत्तरपत्र"],
  [/false\s+complaint/gi, "झुठ्ठा उजुरी"],
  [/civil\s+procedure/gi, "देवानी कार्यविधि"],
  [/criminal\s+procedure/gi, "फौजदारी कार्यविधि"],
  [/civil\s+code/gi, "देवानी संहिता"],
  [/criminal\s+code/gi, "अपराध संहिता"],
  [/jaheri\s+darakhast/gi, "जाहेरी दरखास्त"],
  [/jaheri\s+darta/gi, "जाहेरी दर्ता"],
  [/darta\s+garna\s+manena/gi, "दर्ता गर्न मानेन"],
  [/darta\s+garnu\s+manena/gi, "दर्ता गर्न मानेन"],
  [/court\s+fee/gi, "अदालती शुल्क"],
  [/\bsearch\b/gi, "खानतलासी"],
  [/adalati\s+shulk/gi, "अदालती शुल्क"],
  [/devani\s+mudda/gi, "देवानी मुद्दा"],
  [/faujari\s+mudda/gi, "फौजदारी मुद्दा"],
  [/khanatalasi/gi, "खानतलासी"],
  [/khanatalkashi/gi, "खानतलासी"],
  [/suryoday/gi, "सूर्योदय"],
  [/suryodaya/gi, "सूर्योदय"],
  [/suryoday\s+agi/gi, "सूर्योदय अगि"],
  [/upadafa/gi, "उपदफा"],
  [/upadapha/gi, "उपदफा"],
  [/milapatra/gi, "मिलापत्र"],
  [/jagga\s+michera/gi, "जग्गा मिसिएको"],
  [/ghar\s+banayeko/gi, "घर बनाएको"],
  [/chhimeki\s+le/gi, "छिमेकीले"],
  [/chimeki\s+le/gi, "छिमेकीले"],
  [/faisala\s+hunu\s+aghi/gi, "फैसला हुनु अगि"],
  [/faisala\s+hunu/gi, "फैसला हुनु"],
  [/milapatra\s+bha?e+y?ma/gi, "मिलापत्र भएमा"],
  [/dastur\s+firta/gi, "दस्तुर फिर्ता"],
  [/adalti\s+shulk/gi, "अदालती शुल्क"],
  [/dismiss/gi, "डिसमिस"],
  [/dismis/gi, "डिसमिस"],
  [/pakrau\s+purji/gi, "पक्राउ पुर्जी"],
  [/pakrau/gi, "पक्राउ"],
  [/purji/gi, "पुर्जी"],
  [/hadmyad/gi, "हदम्याद"],
  [/had\s+myad/gi, "हदम्याद"],
  [/after\s+tamel/gi, "तामेल पछि"],
  [/tamel/gi, "तामेल"],
  [/deadline/gi, "म्याद"],
];

export const ROMAN_WORDS: Readonly<Record<string, string>> = {
  pratibadi: "प्रतिवादी",
  prativadi: "प्रतिवादी",
  pratibed: "प्रतिवाद",
  pratuttar: "प्रतिउत्तर",
  pratiuttar: "प्रतिउत्तर",
  pariuttar: "प्रतिउत्तर",
  pratuttarpatra: "प्रतिउत्तरपत्र",
  pratiuttarpatra: "प्रतिउत्तरपत्र",
  likhit: "लिखित",
  patra: "पत्र",
  kati: "कति",
  din: "दिन",
  dinma: "दिनमा",
  dinbhitra: "दिनभित्र",
  bhitra: "भित्र",
  bhhitra: "भित्र",
  bhitr: "भित्र",
  pesh: "पेश",
  garnu: "गर्नु",
  garne: "गर्ने",
  parchha: "पर्छ",
  parxa: "पर्छ",
  parxha: "पर्छ",
  parcha: "पर्छ",
  le: "ले",
  ko: "को",
  ma: "मा",
  ke: "के",
  ho: "हो",
  hunu: "हुनु",
  hune: "हुने",
  mudda: "मुद्दा",
  dafa: "दफा",
  daafa: "दफा",
  dapha: "दफा",
  myad: "म्याद",
  firad: "फिराद",
  firadpatra: "फिरादपत्र",
  adalat: "अदालत",
  abhiyog: "अभियोग",
  ujuri: "उजुरी",
  jaheri: "जाहेरी",
  jaheriwala: "जाहेरवाला",
  darakhast: "दरखास्त",
  darta: "दर्ता",
  prahari: "प्रहरी",
  police: "प्रहरी",
  manena: "मानेन",
  manen: "मानेन",
  inkar: "इन्कार",
  kaha: "कहाँ",
  kahaa: "कहाँ",
  sakchu: "सक्छु",
  sakchhu: "सक्छु",
  garna: "गर्न",
  jhuttha: "झुठ्ठा",
  hatya: "हत्या",
  chori: "चोरी",
  saksh: "साक्ष",
  sakshi: "साक्षी",
  vivah: "विवाह",
  karar: "करार",
  hirasat: "हिरासत",
  anusandhan: "अनुसन्धान",
  kharej: "खारेज",
  firta: "फिर्ता",
  paisa: "पैसा",
  tireko: "तिरेको",
  mero: "मेरो",
  bayema: "भएमा",
  painchha: "पाइन्छ",
  paincha: "पाइन्छ",
  ki: "कि",
  nai: "नै",
  ekkais: "एक्काइस",
  ekkaisa: "एक्काइस",
  sattari: "सत्तरी",
  sapta: "सात",
  panhdra: "पन्ध्र",
  // procedure / evidence
  khanatalasi: "खानतलासी",
  khanatalkashi: "खानतलासी",
  suryoday: "सूर्योदय",
  suryodaya: "सूर्योदय",
  upasthiti: "उपस्थिति",
  upadafa: "उपदफा",
  upadapha: "उपदफा",
  parichhed: "परिच्छेद",
  milapatra: "मिलापत्र",
  dismiss: "डिसमिस",
  dismis: "डिसमिस",
  pakrau: "पक्राउ",
  purji: "पुर्जी",
  thuna: "थुन",
  thunama: "थुनामा",
  abhiyukt: "अभियुक्त",
  abhiyukta: "अभियुक्त",
  abhiyogi: "अभियोगी",
  sarkar: "सरकार",
  wadi: "वादी",
  badi: "वादी",
  nyay: "न्याय",
  nyaya: "न्याय",
  adalati: "अदालती",
  shulk: "शुल्क",
  shulka: "शुल्क",
  fee: "शुल्क",
  search: "खानतलासी",
  devani: "देवानी",
  faujari: "फौजदारी",
  apradh: "अपराध",
  sanghita: "संहिता",
  karvyadhi: "कार्यविधि",
  karyabidhi: "कार्यविधि",
  tamel: "तामेल",
  hadmyad: "हदम्याद",
  mahila: "महिला",
  mahilako: "महिलाको",
  sharir: "शरीर",
  sharirko: "शरीरको",
  agi: "अगि",
  after: "पछि",
  pachi: "पछि",
  agadi: "अगाडि",
  kas: "कस",
  kasko: "कसको",
  kun: "कुन",
  kunai: "कुनै",
  deadline: "म्याद",
  section: "दफा",
  sec: "दफा",
  faisala: "फैसला",
  phaisala: "फैसला",
  phaisla: "फैसला",
  aghi: "अगि",
  bhayema: "भएमा",
  bhaeyma: "भएमा",
  bhaeema: "भएमा",
  bhayeko: "भएको",
  dastur: "दस्तुर",
  daastur: "दस्तुर",
  huncha: "हुन्छ",
  hunncha: "हुन्छ",
  hunxa: "हुन्छ",
  hunxha: "हुन्छ",
  hudaina: "हुँदैन",
  hudiana: "हुँदैन",
  hudain: "हुँदैन",
  paisincha: "पाइन्छ",
  jagga: "जग्गा",
  jaga: "जग्गा",
  chheu: "छेउ",
  cheu: "छेउ",
  chimeki: "छिमेकी",
  chhimeki: "छिमेकी",
  ghar: "घर",
  banayeko: "बनाएको",
  banako: "बनाएको",
  chha: "छ",
  cha: "छ",
  michera: "मिसिएको",
  micheko: "मिसिएको",
  maile: "मैले",
  milcha: "मिल्छ",
  milxa: "मिल्छ",
  milchha: "मिल्छ",
  ft: "फिट",
  feet: "फिट",
  atikraman: "अतिक्रमण",
  simana: "सीमा",
};

/** True when text is mostly Roman letters (not yet Devanagari). */
export function isRomanNepaliText(text: string): boolean {
  const latin = (text.match(/[A-Za-z]/g) ?? []).length;
  const deva = (text.match(/[\u0900-\u097F]/g) ?? []).length;
  return latin >= 3 && latin > deva;
}

/** Attach common postpositions to the preceding Devanagari word (Roman input often splits them). */
export function attachNepaliPostpositions(text: string): string {
  return text
    .replace(/([\u0900-\u097F])\s+ले(?=\s|$|[?.!])/gu, "$1ले")
    .replace(/([\u0900-\u097F])\s+मा(?=\s|$|[?.!])/gu, "$1मा")
    .replace(/([\u0900-\u097F])\s+को(?=\s|$|[?.!])/gu, "$1को")
    .replace(/([\u0900-\u097F])\s+बाट(?=\s|$|[?.!])/gu, "$1बाट")
    .replace(/दिन\s+भित्र/gu, "दिनभित्र");
}

/**
 * Convert known Roman legal spellings to Devanagari without an LLM.
 * Unknown Roman tokens are left as-is for optional LLM follow-up.
 */
export function transliterateRomanNepali(text: string): string {
  let s = text;
  for (const [re, repl] of PHRASE_REPLACEMENTS) {
    s = s.replace(re, repl);
  }
  s = s.replace(/\b([a-zA-Z]+)\b/g, (match) => {
    const lower = match.toLowerCase();
    return ROMAN_WORDS[lower] ?? match;
  });
  return attachNepaliPostpositions(s.replace(/\s+/g, " ").trim());
}
